import tkinter as tk
window=tk.Tk()
window.title("Employee Management System")
window.geometry("700x700")
empid=tk.Label(window,text="Employee ID",fg="red",bg="yellow",font=("Arial",12))
empid.place(x=10,y=25)
eid=tk.Entry(window,width="15",font=("Arial",12))
eid.place(x=150,y=25)
empn=tk.Label(window,text="Employee Name",fg="red",bg="yellow",font=("Arial",12))
empn.place(x=10,y=67)
en=tk.Entry(window,width="15",font=("Arial",12))
en.place(x=150,y=65)
empg=tk.Label(window,text="Gender",fg="red",bg="yellow",font=("Arial",12))
empg.place(x=10,y=110)
male=tk.Radiobutton(window,text="Male",value="M")
male.place(x=150,y=110)
female=tk.Radiobutton(window,text="Female",value="F")
female.place(x=210,y=110)
empc=tk.Label(window,text="Employee City",fg="red",bg="yellow",font=("Arial",12))
empc.place(x=10,y=155)
ec=tk.Entry(window,width="15",font=("Arial",12))
ec.place(x=150,y=155)
empd=tk.Label(window,text="Employee Designation",fg="red",bg="yellow",font=("Arial",12))
empd.place(x=10,y=200)
ed=tk.Entry(window,width="15",font=("Arial",12))
ed.place(x=210,y=200)
emps=tk.Label(window,text="Employee Salary",fg="red",bg="yellow",font=("Arial",12))
emps.place(x=10,y=245)
es=tk.Entry(window,width="15",font=("Arial",12))
es.place(x=180,y=245)
sremp=tk.Button(window,text="Add Emp.",fg="green",bg="yellow",font=("Arial",12))
sremp.place(x=60,y=500)
ademp=tk.Button(window,text="Search Emp.",fg="green",bg="yellow",font=("Arial",12))
ademp.place(x=143,y=500)
shemp=tk.Button(window,text="Show All Emp.",fg="green",bg="yellow",font=("Arial",12))
shemp.place(x=247,y=500)
uemp=tk.Button(window,text="Update Emp.",fg="green",bg="yellow",font=("Arial",12))
uemp.place(x=361,y=500)
demp=tk.Button(window,text="Delete Emp.",fg="green",bg="yellow",font=("Arial",12))
demp.place(x=466,y=500)
quit=tk.Button(window,text="Quit",fg="green",bg="yellow",font=("Arial",12))
quit.place(x=566,y=500)



window.mainloop()
